### ISSUE TITLE
Wiki needs to be moved to github

### ISSUE THREAD

**Issue by edmundhighcock** [edmundhighcock/coderunner#2]
The wiki is currently still on sourceforge and needs to be moved to github. I will get onto this ASAP.

**Comment by edmundhighcock** [comment]
Okay, this is done. Of course the wiki is still very rudimentary, but everything that was on sourceforge is now here.

**Comment by ferdinandvanwyk** [comment]
Great. I'm willing to write the installation documentation once I sort out the dependencies  (#1).

**Comment by ferdinandvanwyk** [comment]
Just had a quick look and it seem like the links to the various wiki pages on this page are broken: https://github.com/coderunner-framework/coderunner/wiki

Seems like you're using an underscore to separate words in the link which aren't in the name of the page you're linking to.

**Comment by edmundhighcock** [comment]
That was an artefact of the conversion using pandoc. all fixed now.
